honeycombio/honeycomb-opentelemetry-go

- CHANGELOG.md
- version.go
Prepares the v0.1.1 release.
- Updates version to v0.1.1
> Prepare v0.1.1 release

- CHANGELOG.md
- version.go
Prepares the v0.1.2 release.
- Updates version to v0.1.2
> Prepare v0.1.2 release

- CHANGELOG.md
- version.go
Prepares the v0.2.0 release.
- Updates version to v0.2.0
> Prepare v0.2.0 release

- go.mod
- go.sum
Updates the launcher commit to latest.
- Closes #78 
Updates the launcher commit in latest commit.
> Update launcher to latest

- CHANGELOG.md
- honeycomb.go
- version.go
> prepare 0.3.0

- .github/dependabot.yml
> chore: Give dependabot PRs a better title

- CHANGELOG.md
- version.go
Prepares the v0.4.1 release.
- Updates version to 0.4.1
> rel: Prepare v0.4.1 release

- CHANGELOG.md
- README.md
- version.go
Release'uhms
(changelog, version, readme)
> rel: prep v0.4.2

- CHANGELOG.md
- README.md
- RELEASING.md
- version.go
new release
- add extra detail to releasing doc
- update version string
- update readme with new otel version
- add entry to changelog
`make test` and `make smoke` still succeed
> rel: prep release v0.5.0

- CHANGELOG.md
- version.go
prep release v0.5.1
- update version in `version.go`
- update `CHANGELOG.md` with changes since last release
> rel: prep release v0.5.1

- go.mod
- go.sum
update launcher to 1.6.0
update launcher to 1.6.0 and go mod tidy
tests and smoke tests still pass
> maint: update launcher to 1.6.0

- OSSMETADATA
active/stable beta, in line with node and python distros
see updates in the readme after merging
> maint: update oss badge to active

- CHANGELOG.md
- version.go
> rel: prepare release 0.5.2

- CHANGELOG.md
- version.go
Release v0.5.4
- Bump version
- Update changelog
> rel: v0.5.4

- CHANGELOG.md
- README.md
- version.go
> rel: prepare release 0.6.0

- CHANGELOG.md
- README.md
- version.go
Releasing upstream metrics API stabilization and updating package import namespacing.
> rel: prepare v0.7.0

- CHANGELOG.md
- RELEASING.md
- version.go
rel: prep release v0.8.0
- update to 0.8.0 in version.go
- update changelog for changes in v0.8.0
- fix formatting in releasing doc
> rel: prep release v0.8.0

- CHANGELOG.md
- README.md
- honeycomb.go
- version.go
> rel: prepare 0.8.1

- README.md
- version.go
new release
- update version to 0.9.0
- update readme with version of otel and otel-config-go being built with
- add minimum go version and link to compatibility matrix
> rel: prep release v0.9.0

- README.md
Updates README title to be at the top of the file to match other repo's structure.
- Moves title to top of file
> maint: Update README title

- OSSMETADATA
Update badge to reflect state of the repo
> maint: update OSSMETADATA
