honeycombio/honeycomb-opentelemetry-go

common.go, honeycomb.go, honeycomb_test.go
This came about when I was playing with the distro last week, running into several issues across different environments (and confusingly, the environment that's a classic environment...). I was tripped up by the use of terms related to direct HTTP headers since I never actually set this values. I also struggled to see the difference between `x-honeycomb-team` and `x-honeycomb-dataset`, thinking to myself "but I have an API key!".
Anyways, here's some proposed changes to the configuration errors.
=> More descriptive errors

honeycomb.go, honeycomb_test.go
When the `DEBUG` env var is set, it should set the log level to "debug" too.
- Closes #51 
- When `DEBUG` env var is detected, set log level to "debug"
=> Set log level to debug when debug option is set

deterministic_sampler.go, deterministic_sampler_test.go, honeycomb_test.go, version.go, version_test.go
All go files should include the standard license header, some are missing it.
- Closes #52
- Add license header to all go files that it was missing for
Each go file now includes the license header.
=> Add missing license headers

baggage_span_processor_test.go
The baggage span processor does not include tests yet, we should add some to verify behaviour.
- Closes #54
- Adds tests for baggage span processor
Tests run that verifies processor behaviour
=> Add baggage processor tests

honeycomb.go, honeycomb_test.go
The launcher base config has a generic Exporter endpoint that we can set instead of the specific traces and metrics endpoints. Traces and metrics endpoints fallback to the generic value if not set directly.
- Closes #50
- Closes #59
- Set the launcher config's ExporterEndpoint value instead of both TracesExporterEndpoint and MetricsExporterEndpoint
- Update existing unit test to verify the value has been set correctly
- When using the distro, both traces and metrics data should continue to set to honeycomb without issue. If a specific traces or metric endpoint is set, it data should be sent there instead.
=> Set base exporter endpoint when setting up vendor opts

RELEASING.md, honeycomb.go, honeycomb_test.go
We want to know which OTLP version is used so we can safely upgrade on the consumer side.
- Closes #63 
Adding the extra `x-otlp-version` header when configuring the distro metadata.
Funny/sad discovery: we can't actually see the `x-otlp-version` in our own telemetry because our instrumentation doesn't capture it :lolsob: Will create follow-up issue to add that.
For now, I was able to see the header in incoming gRPC metadata in local shepherd:
=> feat: add OTLP version header

honeycomb.go, honeycomb_test.go
Adds support for reading and applying honeycomb endpoint environment variables, `HONEYCOMB_API_ENDPOINT`, `HONEYCOMB_TRACES_API_ENDPOINT` and `HONEYCOMB_METRICS_API_ENDPOINT`.
- Closes #62 
- Read and apply the environment variables during `setVendorOptions`
- Add unit test to verify env vars are read and applied to the config
Setting the honeycomb specific env vars results in the distro sending telemetry to the provided endpoint.
=> Add support for Honeycomb endpoint environment variables

honeycomb.go, honeycomb_test.go
Not all Honeycomb users get access to metrics and so it should be an opt-in feature. This change makes metrics disabled by default and can be enabled by either setting the env var `OTEL_METRICS_ENABLED` or using `launcher.WithMetricsEnabled(true)` option.
- Closes #69 
- Default metrics to be disabled
- Check OTEL_METRICS_ENABLED to see if it should be enabled
- Add unit test
The distro will not attempt to send metrics unless they are explicitly enabled.
=> Disable metrics by default

go.mod, go.sum, honeycomb.go, honeycomb_test.go
It can be useful to send telemetry to different endpoints, eg direct vs through a proxy (refinery / collector). This often requires different endpoints and headers. Headers were shared between traces and metrics exporters which meant it wasn't possible.
This PR utilises the new launcher options to set traces and metrics specific headers.
- Closes #71 
- Blocked on https://github.com/honeycombio/opentelemetry-go-contrib/pull/655
- Introduce options to set traces and metrics api key and datasets, both by env var and launcher options
- Add unit tests
You can send traces and metrics telemetry with different api keys and dataset headers.
=> Add support for separate traces and metrics API key and dataset

examples/webhook-listener-triggers/README.md
#68 added a timestamp field to the example readme which is actually not passed as part of the trigger, and is added by the go program. This is very confusing as this example is linked from the Honeycomb documentation as an example of the trigger payload! This removes that field from the readme but doesn't touch the go program.
=> Remove timestamp field from example trigger hook

README.md, RELEASING.md
Readme lists which OTel version is currently bundled in the distro
- fix typos
- add releasing step to update otel version in readme
=> maint: update readme with latest otel version

honeycomb.go, honeycomb_test.go
This fixes https://github.com/honeycombio/honeycomb-opentelemetry-go/issues/97
But goes further since we had that discussion around not emitting an error on misconfiguration.
=> fix: Don't error on misconfiguration; warn instead

CHANGELOG.md, README.md, version.go
Prepares the v0.4.0 release.
- Updates version to 0.4.0 in version.go
- Updates OTel SDK version in README
=> rel: Prepare v0.4.0 release

honeycomb.go, honeycomb_test.go
Messages printed by the SDK should use the provided logger and not print directly to the console.
Not sure on if we should fall back to `fmt.Println` if no logger has been provided? A default one is provided by the launcher which uses `fmt` so it feels like if you override it to `nil` then that is your own rake to step on.
When we print errors with the configuration we now use the configured logger.
run the tests
=> fix: Use configured logger to print messages

.circleci/config.yml
- closes #106 
Add smoke tests to circleci config. Smoke tests are run in nightly runs with regular test, as well as on builds (requiring test to succeed) and as a requirement for publishing to Github
[check it out in circle](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-go/309/workflows/64fb5b6a-d1e9-4b5c-83fe-c18c47217c06/jobs/641)! should see passing tests and uploaded artifacts.
=> maint: add smoke test to circle

.circleci/config.yml
Added `filters` for `smoke-tests` job because CircleCI needs filters for every job if there are filters for a single job. This was preventing other steps like `publish-github`.
- Added a filters section that allows smoke tests to run on every push.
- Smoke tests should run in CI: https://github.com/honeycombio/honeycomb-opentelemetry-go/pull/110/checks?check_run_id=10760320583
=> ci: fix filters for smoke-tests job

.circleci/config.yml
Go 1.20 was released in February!
Add 1.20 to test matrix and use as default version
tests still pass
=> ci: add go 1.20 to ci

README.md, examples/baggage/example.go, examples/baggage/go.mod, examples/baggage/go.sum, examples/webhook-listener-triggers/go.mod, examples/webhook-listener-triggers/go.sum, examples/webhook-listener-triggers/main.go, go.mod, go.sum, honeycomb.go, honeycomb_test.go
`otel-launcher-go` has been renamed to `otel-config-go`, this PR handles that name change
- Use `otel-config-go` package instead of `otel-launcher-go` package
- Rename `launcher` to `otelconfig` everywhere
=> maint: otel-launcher-go rename to otel-config-go

.circleci/config.yml, .gitignore, smoke-tests/docker-compose.yml
- Closes #150 
- update ubuntu to newer image for smoke test (this was the actual fix)
- update collector to newer version
- gitignore smoke test output from local tests
all tests pass in Circle ([success](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-go/580/workflows/7fb6e477-ce51-4137-869c-4ee0d44c1f06/jobs/1520)) and with local tests
=> maint: update ubuntu and collector versions in CI

.github/release.yml
- auto-generated release notes put all dependency bumps into "other changes"
- add label type:dependencies to maintenance category for release notes
next time we auto-generate notes for a release that includes a dependabot update, it should show up in the maintenance category
=> maint: add label type:dependencies to maintenance category for release notes

.github/dependabot.yml
- easier dependency updates
- add groups for main package
- add example dirs to dependabot
next dependabots should group otel dependencies, and also include updates for examples
=> maint: add dependabot groups and include example directories

honeycomb.go, honeycomb_test.go
We've now released Ingest Keys, but in order for them to work with Classic environments properly we need to update the key detection logic.
- updates the Classic API Key detection logic to understand the shape of a Classic Ingest Key
=> feat: support Classic Ingest Keys

CHANGELOG.md, README.md, version.go
Prepares the next release of this library.
- Update version to v0.10.0
- Add changelog entry (and missing one for v0.9.0)
=> rel: Prepare v0.10.0 release
